
WarpDepleteDB = {
	["profileKeys"] = {
		["Jarpd - Tarren Mill"] = "Default",
		["Mageblob - Archimonde"] = "Default",
		["Jarmk - Tarren Mill"] = "Default",
		["Jarw - Tarren Mill"] = "Default",
		["Jardr - Tarren Mill"] = "Default",
		["Jarpd - Twisting Nether"] = "Default",
		["Jarwl - Tarren Mill"] = "Default",
		["Jardk - Tarren Mill"] = "Default",
		["Jarht - Tarren Mill"] = "Default",
		["Goblinmage - Wildhammer"] = "Default",
		["Jarmk - Twisting Nether"] = "Default",
		["Jyr - Ravencrest"] = "Default",
		["Jarpp - Tarren Mill"] = "Default",
		["Bunnyhoppy - Draenor"] = "Default",
		["Jarxd - Tarren Mill"] = "Default",
		["Jarwr - Tarren Mill"] = "Default",
		["Jarev - Tarren Mill"] = "Default",
	},
	["global"] = {
		["mdtAlertShown"] = true,
	},
	["profiles"] = {
		["Default"] = {
			["keyFontSize"] = 30,
			["timerSuccessColor"] = "ffffd338",
			["bar2FontSize"] = 18,
			["timerFontSize"] = 30,
			["deathsColor"] = "ffff8686",
			["forcesGlowLineCount"] = 30,
			["keyFontFlags"] = "THICKOUTLINE",
			["forcesFormat"] = ":count:/:totalcount: - :percent:",
			["frameX"] = -9.742046356201172,
			["currentPullFormat"] = "(+:count: - :percent:)",
			["keyDetailsFontSize"] = 18,
			["bar3FontSize"] = 18,
			["keyDetailsColor"] = "ff00c9ff",
			["frameY"] = 88.20565795898438,
			["bar1FontSize"] = 18,
			["forcesOverlayTextureColor"] = "ffff7800",
			["forcesTextureColor"] = "ff00ff00",
			["deathsFontSize"] = 20,
			["forcesFontSize"] = 20,
			["keyColor"] = "ffffffff",
			["timerFontFlags"] = "THICKOUTLINE",
		},
	},
}
